version: '2'
services:

    striim-node:
        image: "striim.azurecr.io/striim/striim-node:3.8.2A"
        ports:
            - "9080"
        env_file:
            - striim-node.env
        volumes:
            - ./extlib:/opt/striim/extlib   
            - striim-data:/var/striim 
            - striim-waction:/opt/striim/data  

                
            
volumes:
    striim-data: 
    striim-waction:      
